vignettes/estimate_smooth.Rmd

fix link to data in the vignettes

---

DESCRIPTION
R/estimate_slopes.R

Merge when https://github.com/easystats/datawizard/pull/126

data_match fix (modelbased)

---

.github/workflows/pkgdown.yaml
_pkgdown.yml

https://github.com/easystats/easystats/issues/186

Use new pkgdown template

---

DESCRIPTION
NEWS.md
R/estimate_predicted.R
R/estimate_slopes.R
R/print.R
R/reshape_grouplevel.R
R/visualisation_recipe.estimate_predicted.R
R/visualisation_recipe.estimate_slopes.R
README.Rmd
man/estimate_slopes.Rd
man/visualisation_matrix.Rd
man/visualisation_recipe.estimate_predicted.Rd
tests/testthat/test-estimate_contrasts.R
tests/testthat/test-estimate_expectation.R
tests/testthat/test-estimate_predicted.R
tests/testthat/test-glmmTMB.R
tests/testthat/test-mgcv.R
vignettes/derivatives.Rmd
vignettes/estimate_response.Rmd

fix adjusted_for attr

---

R/describe_nonlinear.R
R/estimate_predicted.R
R/get_emmeans.R
R/get_emtrends.R
R/get_marginaleffects.R
R/smoothing.R
R/visualisation_matrix.R
R/visualisation_recipe.estimate_means.R
R/visualisation_recipe.estimate_predicted.R
R/visualisation_recipe.estimate_slopes.R
R/zero_crossings.R

https://github.com/easystats/easystats/issues/263

Leave out function call in condition messages

---

README.Rmd

https://github.com/easystats/easystats/issues/271

Add lifecycle badge

---

DESCRIPTION
R/get_marginalmeans.R
tests/testthat/test-get_marginaleffects.R

get_marginalmeans(..., by=NULL) should return the overall marginal mean

---

DESCRIPTION
NEWS.md
R/estimate_contrasts.R
R/format.R
R/get_emcontrasts.R
R/get_emmeans.R
R/get_marginalcontrasts.R
R/smoothing.R
R/zero_crossings.R
man/estimate_contrasts.Rd
man/get_emmeans.Rd
tests/testthat/test-estimate_contrasts.R

Rename `method` into `comparison` in `estimate_contrasts()`

---

DESCRIPTION
NEWS.md
R/estimate_contrasts.R
R/get_emcontrasts.R
man/estimate_contrasts.Rd
man/get_emmeans.Rd
tests/testthat/test-estimate_contrasts.R

methods other than "pairwise" for `estimate_contrasts()` fail

---

DESCRIPTION
R/format.R
R/utils.R
tests/testthat/test-glmmTMB.R

Wrong column header for ZI-probabilities

---

DESCRIPTION
R/format.R
R/visualisation_recipe_internal.R
tests/testthat/_snaps/windows/print.md
tests/testthat/test-print.R

Protect integers in output

---

R/estimate_grouplevel.R
R/utils.R

Remove the internal utility `.to_numeric()`?

---

R/visualisation_recipe.R
R/visualisation_recipe_internal.R
man/visualisation_recipe.estimate_predicted.Rd
tests/testthat/_snaps/plot/plot-means-no-ci-1.svg
tests/testthat/_snaps/plot/plot-means-no-ci-2.svg
tests/testthat/_snaps/plot/plot-means-no-ci-3.svg
tests/testthat/test-plot.R

@DominiqueMakowski this is not urgent, but what do you think about having an option to remove the CI in plots?

option to show/hide CI

---

DESCRIPTION
tests/testthat/test-attributes_estimatefun.R
tests/testthat/test-estimate_means.R
tests/testthat/test-glmmTMB.R
tests/testthat/test-mgcv.R

Need to skip tests that fail with CRAN version.

Test with CRAN version of {marginaleffects}

---

DESCRIPTION
NEWS.md
R/pool.R
R/table_footer.R
R/visualisation_recipe.R
R/visualisation_recipe_internal.R
man/visualisation_recipe.estimate_predicted.Rd
tests/testthat/_snaps/plot-flexible_numeric/plot-auto-numeric-by-1.svg
tests/testthat/_snaps/plot-flexible_numeric/plot-auto-numeric-by-2.svg
tests/testthat/_snaps/plot/plot-expectation-fivenum-2.svg
tests/testthat/_snaps/plot/plot-expectation-fivenum.svg
tests/testthat/_snaps/plot/plot-logistic-bounds-2.svg
tests/testthat/test-mice.R
tests/testthat/test-plot-flexible_numeric.R
tests/testthat/test-plot.R

Fixes #201 
```r
library(modelbased)
set.seed(1234)
x1 <- rnorm(200)
x2 <- rnorm(200)
y <- 2 * x1 + x1^2 + 4 * x2 + rnorm(200)
d <- data.frame(x1, x2, y)
model <- lm(y ~ x1 + x2, data = d)
pr <- estimate_means(model, c("x1", "x2"))
plot(pr)
```
```r
pr <- estimate_means(model, c("x1", "x2 = [sd]"))
plot(pr)
```

Plot 2nd numeric in by as continuous or factor, based on number of unique values

---

DESCRIPTION
NEWS.md
R/estimate_predicted.R
R/format.R
R/print.R
R/table_footer.R
man/print.estimate_contrasts.Rd
tests/testthat/test-multivariate_response.R
vignettes/estimate_slopes.Rmd

.estimate_predicted() with multivariate or matrix responses

---

DESCRIPTION
NEWS.md
R/get_emcontrasts.R
man/get_emmeans.Rd
tests/testthat/test-estimate_contrasts.R

Contrasting slopes: differences between backends

---

DESCRIPTION
R/format.R
tests/testthat/test-scoping_issues.R

`estimate_contrasts()` fails if object contrast is defined in environment

---

DESCRIPTION
NEWS.md
R/get_marginaltrends.R
inst/WORDLIST
tests/testthat/_snaps/plot/plot-slopes-5.svg
tests/testthat/test-estimate_slopes.R

Issues with random effects: estimate_slopes and estimate_contrasts failures using the marginaleffects backend

---

DESCRIPTION
R/get_marginalcontrasts.R

Bug: estimate_contrasts failing with basic example

---

DESCRIPTION
R/visualisation_recipe_internal.R
tests/testthat/_snaps/plot-grouplevel/plot-grouplevel-bayes-1.svg
tests/testthat/_snaps/plot-grouplevel/plot-grouplevel-bayes-2.svg
tests/testthat/_snaps/plot-grouplevel/plot-grouplevel-bayes-3.svg
tests/testthat/_snaps/plot-grouplevel/plot-grouplevel-bayes-4.svg
tests/testthat/_snaps/plot-grouplevel/plot-grouplevel-bayes-5.svg
tests/testthat/_snaps/plot/plot-grouplevel-lme4-1.svg
tests/testthat/_snaps/plot/plot-grouplevel-lme4-2.svg
tests/testthat/test-plot-grouplevel.R
tests/testthat/test-plot.R

In `estimate_grouplevel()`, use `facet_wrap()` instead all parameters and components in one plot

---

DESCRIPTION
NEWS.md
R/estimate_slopes.R
R/get_marginalcontrasts.R
R/get_marginaltrends.R
man/estimate_slopes.Rd
man/get_emmeans.Rd
tests/testthat/test-attributes_estimatefun.R
tests/testthat/test-transform_response.R

Transform ignored for estimate_constrast on continuous variable

---

DESCRIPTION
R/estimate_means.R
R/estimate_predicted.R
R/get_marginaltrends.R
man/estimate_contrasts.Rd
man/estimate_expectation.Rd
man/estimate_means.Rd
man/estimate_slopes.Rd
man/get_emmeans.Rd
man/pool_predictions.Rd
tests/testthat/test-attributes_estimatefun.R
tests/testthat/test-transform_response.R

Consistency in output when `transform = TRUE`

---

R/estimate_grouplevel.R
inst/WORDLIST
man/estimate_grouplevel.Rd
paper/paper.Rmd

@bwiernik could you take a quick look at the docstring changes here to be sure I haven't misclarified the BLUPs?

[docs] grouplevel

---

DESCRIPTION
NEWS.md
R/visualisation_recipe_internal.R
inst/WORDLIST
tests/testthat/_snaps/plot-slopes/plot-slopes-y-axis-labels-1.svg
tests/testthat/_snaps/plot-slopes/plot-slopes-y-axis-labels-2.svg
tests/testthat/test-plot-slopes.R

Question about the Johnson_Neyman plot axis labeling..

---

DESCRIPTION
NEWS.md
R/estimate_slopes.R
R/get_marginaltrends.R
man/estimate_slopes.Rd
man/get_emmeans.Rd
tests/testthat/test-estimate_slopes.R

Trend within range

---

DESCRIPTION
NEWS.md
R/get_marginalcontrasts.R
tests/testthat/test-estimate_contrasts.R

Better error message

---

DESCRIPTION
NEWS.md
R/clean_names.R
R/estimate_contrast_methods.R
R/estimate_predicted.R
R/format.R
R/get_emcontrasts.R
R/get_emmeans.R
R/get_emtrends.R
R/get_marginalcontrasts.R
R/get_marginalmeans.R
R/get_marginaltrends.R
R/standardize_methods.R
R/table_footer.R
R/visualisation_recipe_internal.R
tests/testthat/test-brms.R

```r
m <- insight::download_model("brms_mv_1")
modelbased::estimate_means(m, by = "wt")
marginaleffects::avg_predictions(m, variables = "wt", newdata = "balanced")
```

Fix miltivariate brms models

---

DESCRIPTION
NEWS.md
R/estimate_predicted.R
man/estimate_expectation.Rd
tests/testthat/test-estimate_predicted.R

estimate_prediction() is extremely slow compared to insight::get_predicted() for Wiener

---

DESCRIPTION
NEWS.md
R/estimate_contrasts.R
R/estimate_contrasts_effectsize.R
R/format.R
R/get_emcontrasts.R
R/get_marginalcontrasts.R
R/get_marginalmeans.R
R/joint_test.R
R/table_footer.R
man/estimate_contrasts.Rd
man/get_emmeans.Rd
tests/testthat/test-attributes_estimatefun.R
tests/testthat/test-joint_test.R
tests/testthat/test-keep_iterations.R

Allow joint-test for factorial designs

---

DESCRIPTION
R/estimate_contrasts.R
R/format.R
R/get_inequalitycontrasts.R
R/get_marginalcontrasts.R
R/print.R
man/estimate_contrasts.Rd
man/get_emmeans.Rd
tests/testthat/test-estimate_contrasts.R
vignettes/practical_inequalities.Rmd

inequality ratio can be pairwise

---

DESCRIPTION
NEWS.md
R/get_marginalcontrasts.R
tests/testthat/test-estimate_contrasts.R

estimate_contrasts docs don't match for Helmert

---

DESCRIPTION
NEWS.md
inst/WORDLIST
tests/testthat/test-estimate_grouplevel.R

Add tests for estimate_grouplevel.coxme
